name: 'size-limit-action'
description: 'size-limit action'
author: 'Andres Alvarez <a.alvarez.sor@gmail.com>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  build_script:
    required: false
    description: 'a custom npm script to build'
  skip_step:
    required: false
    description: 'which step to skip, either "install" or "build"'
  update_review:
    required: false
    description: "will update the previous review if the status hasn't changed"
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
