name: 'size-limit-action'
description: 'size-limit action'
author: 'Andres Alvarez <a.alvarez.sor@gmail.com>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  build_script:
    required: false
    description: 'a custom npm script to build'
  skip_step:
    required: false
    description: 'which step to skip, either "install" or "build"'
  base_size_path:
    required: false
    description: 'path to base branch size file, when set used directly'
  head_size_path:
    required: false
    description: 'path to base branch size file, when set used directly'
runs:
  using: 'node12'
  main: 'dist/index.js'
